### ISSUE TITLE
Original SHT throws error on 1.9

### ISSUE THREAD

**Issue by TNTUP** [AddstarMC/SimpleHelpTickets#1]
Hi, sorry for writing a issue here, I'm asking if you still work on it for 1.9? I haven't tried cloning your source code and mvn it, I'll do tests on my 1.9 test server.

EDIT: It throws error like i'm missing BungeeChat? It means this plugin is meant to run on Bungee instances? If so, hell no I won't go to bungee for reasons.

[18:13:13 INFO]: QCFB issued server command: /ticket fdksahf probl;em

org.bukkit.command.CommandException: Unhandled exception executing command 'ticket' in plugin SimpleHelpTickets v1.3.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1313) [spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1148) [spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NoClassDefFoundError: au/com/addstar/bc/BungeeChat
        at me.odium.simplehelptickets.SimpleHelpTickets.notifyAdmins(SimpleHelpTickets.java:659) ~[?:?]
        at me.odium.simplehelptickets.commands.ticket.NotifyItemOpened(ticket.java:347) ~[?:?]
        at me.odium.simplehelptickets.commands.ticket.onCommand(ticket.java:294) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        ... 15 more
Caused by: java.lang.ClassNotFoundException: au.com.addstar.bc.BungeeChat
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_72]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]
        at me.odium.simplehelptickets.SimpleHelpTickets.notifyAdmins(SimpleHelpTickets.java:659) ~[?:?]
        at me.odium.simplehelptickets.commands.ticket.NotifyItemOpened(ticket.java:347) ~[?:?]
        at me.odium.simplehelptickets.commands.ticket.onCommand(ticket.java:294) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.jar:git-Spigot-dd155ed-3e3516e]
        ... 15 more

**Comment by alchemistmatt** [comment]
This is a bukkit plugin.  It sends messages to the BungeeChat plugin which relays those messages to the master Bungee proxy.  Without forking and modifying the code, I don't believe there is a way to avoid the requirement that BungeeChat-Bukkit.jar also be in your plugins folder.  I suspect you could have that jar file present, but not be running a central Bungee proxy and SimpleHelpTickets will still work.

**Comment by TNTUP** [comment]
I don't have that plugin in my folder, I should have it? Its running from spigot 1.9 directly.

**Comment by alchemistmatt** [comment]
Download BungeeChat-Bukkit-1.0.1.83.jar from http://jenkins.addstar.com.au/job/BungeeChat/  and restart Spigot and see what happens.

**Comment by TNTUP** [comment]
I got the error which cannot connect to redis instance which I don't know what it is and never used it. I hope it wont require myself to go on bungee

**Comment by alchemistmatt** [comment]
Since the sole purpose of adding BungeeChat-Bukkit-1.0.1.83.jar is to satisfy the dependency on au/com/addstar/bc/BungeeChat you can likely just ignore all BungeeChat errors and continue to test / use the SimpleHelpTickets plugin.  Reply back here if you get it working.  You'll need to configure a database for tracking tickets; edit the `SimpleHelpTickets/config.yml` file

**Comment by TNTUP** [comment]
oi okey! Uh well the plugin does crash the server because it is unavailable. Well then, i'll drop trying this plugin xD Sorry for wasting your time, I wanted to keep this plugin but the original dev isn't active anymore :/ Sorry again

**Comment by addstar** [comment]
It would actually be fairly trivial to add a config option to disable the BungeeChat integration, thus allowing you to run it on our server without requiring BungeeChat.
If it's really important to you we could add it?

**Comment by TNTUP** [comment]
uh well I'm not aware if theres an option to disable it. I don't like asking up things just for me, feel free to do so if you wish^^

**Comment by addstar** [comment]
It should only take 5 minutes to add this change and I'm happy to help out if that's the only thing stopping you from continuing to use it. I know how annoying it is to lose an important plugin that your players are used to. But we just are lucky that we are also developers so we can often "revive" plugins that we use that are abandoned.

The config option to disable BungeeChat doesn't exist, but as I say, I'm happy to add this in if you are still interested in using it? (just need to find some time over the weekend)

Just be aware the code here is solely maintained for our own server and while you are free to use them it any way, we can't provide you with any support ;) But you're always welcome to suggest improvements, report bugs and submit PRs, and we'll see what we can do.

**Comment by TNTUP** [comment]
Well, that's not the only plugin which is stopping me, but it will be appreciated if you can XD No rush, take your time for it and I'll take the risk of no support. 

Thanks for your time addstar, very appreciated^^ Didn't expected you offer me to add it haha xD

**Comment by addstar** [comment]
All done.. you can try out build #9 at:
http://jenkins.addstar.com.au/job/SimpleHelpTickets/  :grin:

**Comment by TNTUP** [comment]
Thanks addstar! Works as expected :D :heart:
